### ISSUE TITLE
Heroku access

### ISSUE THREAD

**Issue by rylanbranch** [g5search/devops-access#95]
Need access to https://dashboard.heroku.com/teams/centralized-apps/ for rylan.branch@getg5.com

**Comment by randyleighton** [comment]
Hi Rylan, I sent a slack message on the 20th

From slack:
"Hi Rylan, I saw the request for access to centralized apps. Can you give me the reason you are after all of those, I had to remove a lot of people from that because of the request from engineering leadership. I can send a message with the reason and get you added back if they approve it
if you just need some specific ones let me know also, might be easier to get"

**Comment by randyleighton** [comment]
once we get the 2fa validations for the required team, we can get this done for the 2 apps you need.

**Comment by randyleighton** [comment]
ok done
