### ISSUE TITLE
Access to CMS Prime

### ISSUE THREAD

**Issue by boniattirodrigo** [g5search/devops-access#96]
I want to deploy to prime but when I run ` kubectl config get-contexts` I don't see it.

**Comment by randyleighton** [comment]
Have you gone through the setup documents for GCP and installing the G5 CLI?

https://www.g5devops.com/gcp/

I do see you have access in GCP to deploy to prime. 

If you did set it up already, maybe reach out to the devops channel with what you have done and what you are trying to do.

I am closing this ticket up because you have access to the gcp project you need to deploy.
